### ISSUE TITLE
Not compile with gstreamer 1.8.2

### ISSUE THREAD

**Issue by idreamerhx** [alessandrod/gst-rtsp-cam#1]
Thanks for your project.

It's not compile with  gstreamer 1.8.2 and gstreamer-rtsp-server-1.0

gst-rtsp-cam-media-factory.c:103:22: error: 'GstRTSPMediaFactoryClass {aka struct _GstRTSPMediaFactoryClass}' has no member named 'get_element'; did you mean 'create_element'?
